name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  about:
    path: about
  core:
    path: core
  animate_do: ^3.3.4
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  movie:
    path: movie
  intl: ^0.19.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  search:
    path: search
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  tv:
    path: tv


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
