name: search
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  core:
    path: ../core
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  movie:
    path: ../movie
  rxdart: ^0.28.0
  tv:
    path: ../tv

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg