name: movie
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  core:
    path: ../core
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg